#+title: Learn Yocto


* Source directory structure 

** Top-level core components

*** bitbake/
- This directory includes a copy of BitBake for ease of use. The copy
  matches the current stable BitBake release from the BitBake
  project.
- BitBake, a Metadata interpreter, reads the Yocto project Metadata
  and runs the tasks defined by that data.
- Failures are usually from the Metadata and not from BitBake
  itself. Consequently most users do not need to worry about BitBake.

*** build/
- This directory contains user configuration files and output
  generated by the OpenEmbedded build system in its standard
  configuration where the source tree is combined with the output.
- The Build directory is created initially when you source the
  OpenEmbedded build environment setup script (i.e oe-init-build-env).

*** documentation/
- This directory holds the source for the Yocto Project documentation
  as well as templates and tools that allow you to generate PDF and
  HTML versions of the manuals.

*** meta/
- This directory contains the OpenEmbedded-Core metadata. The
  directory holds recipes, common classes, and machine configuration
  for emulated targets (qemux86, qemuarm, and so forth.)

*** meta-poky/



 
